apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
    POSTGRES_DB: "{{ db_name | b64encode }}"
    POSTGRES_USER: "{{ db_user | b64encode }}"
    POSTGRES_PASSWORD: "{{ db_password | b64encode }}"