apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
    tier: database
  namespace: default
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
      - name: postgres
        image: "{{ db_image }}"  # PostgreSQL
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata 
        ports:
        - containerPort: 5432  # Default PostgreSQL port
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data  # Mounting the volume to PostgreSQL's default data directory
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: "{{ pvc_name }}"
