- name: Create a Kubernetes Secret for Moonshot
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'moonshot-secret.yml') | from_yaml }}"
    wait: true
    wait_timeout: 600
  tags: moonshot


- name: Create a Deployment for Moonshot
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'moonshot-deployment.yml') | from_yaml }}"
    wait: true
    wait_timeout: 600
  tags: moonshot

- name: Create a Service for Moonshot
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'moonshot-service.yml') | from_yaml }}"
    wait: true
  tags: moonshot

- name: Wait till Moonshot pod is created
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: default
    label_selectors:
      - app=moonshot
    wait: true
    wait_sleep: 5
    wait_timeout: 180
  register: moonshot_pod_info

- name: Check if seed_database flag is true
  debug:
    msg: "Flag seed_database is set to true, running database seed"
  when: seed_database | default(false)

- name: Populate the Postgres database
  kubernetes.core.k8s_exec:
    namespace: default
    pod: "{{ moonshot_pod_info.resources[0].metadata.name }}"
    command: python3 seed.py
  register: result_seed
  retries: 5
  delay: 5
  until: result_seed.rc == 0
  when: seed_database == "true"

- name: Wait for the LoadBalancer Service to become available
  kubernetes.core.k8s_info:
    kind: Service
    namespace: default
    label_selectors:
      - "app=moonshot"
  register: moonshot_info
  retries: 10
  delay: 5
  until: moonshot_info.resources[0].status.loadBalancer | length > 0

- name: Assigning the IP to the app_ip variable
  set_fact:
    app_ip: "{{ moonshot_info.resources[0].status.loadBalancer.ingress[0].ip }}"

- name: Display access IP address
  debug:
    var: app_ip

- name:  Changing the value of the app_ip variable in the all.yml file
  replace:
    path: inventory/gcp.yml
    regexp: "app_ip:.*"
    replace: "app_ip: '{{ app_ip }}'"

- name: Implement the Hpa 
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'moonshot-hpa.yml') | from_yaml }}"
    wait: yes
    wait_timeout: 300
  tags: ['hpa']