- name: "Install MySQL & Swap with Docker"
  hosts: dockerswap
  gather_facts: false
  vars_files:
    - group_vars/secret.yml
  roles:
    - role: docker-mysql
      tags: ["mysql"]

    - role: docker-swap
      tags: ["swap"]
