apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: moonshot-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: {{ moonshot_replicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: moonshot-deployment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
