apiVersion: v1
kind: Secret
metadata:
  name: moonshot-secret
  namespace: default
type: Opaque
data:
    DB_HOST: "{{ db_host | b64encode }}"
    DB_DATABASE: "{{ db_name | b64encode }}"
    DB_USER: "{{ db_user | b64encode }}"
    DB_PASSWORD: "{{ db_password | b64encode }}"